### ISSUE TITLE
Bug: Getting an error when using the addon [1.0.4]

### ISSUE THREAD

**Issue by burekas7** [pustovitDmytro/areace#4] opened 2024-01-20 20:40 UTC
Hi, @pustovitDmytro 
I'm trying to use the addon and I'm getting na error.

The steps are:
- I created a bot using "BotFather" and got a token.
- I put it in the addon settings and enable it.
- I created a new private group, added the bot as a member and then as an admin
- I forward a video from another group to my group.
- When I press on the addon in kodi, I get this error.

Why?

```
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                 Error Type: <class 'KeyError'>
                 Error Contents: 'result'
                 Traceback (most recent call last):
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\script.areace\script.py", line 7, in <module>
                     main()
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\script.areace\script.py", line 4, in main
                     main_dialog()
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\script.areace\resources\main_dialog.py", line 6, in main_dialog
                     items = load_data()
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\script.areace\resources\data_loader.py", line 18, in load_data
                     return load_telegram(settings)
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\script.areace\resources\data_loader.py", line 13, in load_telegram
                     return fetch(opts)
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\script.areace\resources\telegram.py", line 13, in fetch
                     for update in json['result']:
                 KeyError: 'result'
                 -->End of Python script error report<--
```

**Comment by pustovitDmytro** [comment] 2024-01-20 22:38
Hi, I'll look it over, but unfortunately, the addon most likely won't work on Windows. It is based on the [StartAndroidActivity](https://github.com/pustovitDmytro/areace/blob/1f8b1b7e130494cec89601d69fbb57102626984a/resources/main_dialog.py#L10C14-L10C34) command, which won't function correctly on Windows

**Comment by pustovitDmytro** [comment] 2024-01-21 00:28
Please follow the link `https://api.telegram.org/bot<your token>/getUpdates` and attach the JSON response to the issue so that I can reproduce it.

**Comment by burekas7** [comment] 2024-01-21 22:34
> Please follow the link `https://api.telegram.org/bot<your token>/getUpdates` and attach the JSON response to the issue so that I can reproduce it.

`{"ok":true,"result":[]}`

**Comment by burekas7** [comment] 2024-02-08 16:09
@pustovitDmytro 
Hi,
Any update?

**Comment by pustovitDmytro** [comment] 2024-02-09 12:41
Hi,

Your response

```
{"ok":true,"result":[]}
```

indicates that the Telegram bot **is not** receiving any updates from a channel. "Areace" can't display anything without Telegram updates. However, this payload successfully passes all my tests. The expected result is an empty list in translations (and not an error).

As I understand from the error, it could happen if Telegram returns something with "ok":true but without "result". Unfortunately, I couldn't reproduce that and didn't find anything in the Telegram API documentation. So, I decided to close it with the "can't reproduce" label for now.

The only advice I can give here is to install the latest version and verify that the token is entered correctly (it should be in the format `123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11`).

**Closed as completed by pustovitDmytro** 2024-02-09 12:41 UTC
Labels: bug, can't reproduce
